WebApplication2/WebApplication2/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [MinLength(3, ErrorMessage ="Invalid Name")]
        public string Name { get; set; }
        
        [Required] 
        [EmailAddress(ErrorMessage ="Invalid Email")]
        public string Email { get; set; }
        
        [Required]
        [MaxLength(100, ErrorMessage = "Too Long")]
        public string Subject { get; set; }
        
        [Required]
        [MaxLength(250, ErrorMessage ="Too Long")]
        public string Message { get; set; }
    }
}

WebApplication2/WebApplication2/ViewModels/ShopViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.ViewModels
{
    public class ShopViewModel
    {
        public string Category { get; set; }
    }
}

WebApplication2/WebApplication2/Controllers/AppController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data;
using WebApplication2.Services;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailservice;
        private readonly WebContext _ctx;
        private readonly IWebRepository _rep;

        public AppController(IMailService mailservice, WebContext ctx, IWebRepository rep)
        {
            _mailservice = mailservice;
            _ctx = ctx;
            _rep = rep;
        }

        [HttpGet("/")]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost("/")]
        public IActionResult Index(object model)
        {
            return View();
        }
        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _mailservice.SendMessage("ali123@gmail.com", model.Subject, model.Message);
                ViewBag.UserMessage = "Mail sent";
                ModelState.Clear();
            }
            else 
            {
                System.Diagnostics.Debug.WriteLine(false);
            }

            //System.Diagnostics.Debug.WriteLine(model);
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        [HttpGet("shop")]
        public IActionResult Shop()
        {
            var results = _ctx.Products
                .OrderBy(p => p.Category)
                .ToList();

            return View(results);
        }
        [HttpPost("shop")]
        public IActionResult Shop(ShopViewModel model)
        {
            /*var results = _ctx.Products
                .OrderBy(p => p.Category)
                .ToList();
*/
            var results = _rep.GetAllProductsByCategory(model.Category);
            //return View(results);
            return View();
        }
    }
}

WebApplication2/WebApplication2/Views/App/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "About Us";
    Layout = "_Layout";
}
<div>
    <p>Visiting About PAGE.</p>
</div>

WebApplication2/WebApplication2/Views/App/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ContactViewModel
@{
    ViewBag.Title = "Contact Page";
    Layout = "_Layout";
}
@section scripts {
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>">
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
} 
<div>
    <form method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <label>Name: </label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
        <br />
        <label>Email: </label>
        <input type="email" asp-for="Email" />
        <span asp-validation-for="Email"></span>
        <br />
        <label>Subject: </label>
        <input asp-for="Subject" />
        <span asp-validation-for="Subject"></span>
        <br />
        <label>Message: </label>
        <input asp-for="Message" />
        <span asp-validation-for="Message"></span>
        <br />
        <button type="submit">Submit</button>
    </form>
</div>

WebApplication2/WebApplication2/Views/App/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "homepage";
    Layout = "_Layout";
}
<div>
    <ul>
        <li><a asp-controller="App" asp-action="Index">Home</a></li>
        <li><a asp-controller="App" asp-action="Shop">Shop</a></li>
        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        <li><a asp-controller="App" asp-action="About">About</a></li>
    </ul>
    <form method="post">
        <label>Username: </label>
        <input name="username"/>
        <br />
        <label>Password: </label>
        <input type="password" name="password"/>
        <br />
        <button type="submit">Submit</button>
    </form>
</div>

WebApplication2/WebApplication2/Views/App/Shop.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@*@model ShopViewModel*@

@{
    Layout = "_Layout";
    ViewBag.Title = "Shop";
}

@model IEnumerable<Product>

<p>Count: @Model.Count()</p>

@foreach (var p in Model)
{
    <li>@p.Title</li>
}


@*
    <h1>Shop</h1>
    <div>
        <form method="post">
            <label>Category</label>
            <input name="category" asp-for="Category" />
            <br />
            <button type="submit">Submit</button>
            <br />
        </form>
    </div>
*@